# Tensor 생성
- 파이토치에서 데이터를 저장하는 자료구조
- ndarray와 성격, 사용법이 유사하다.

##  원하는 형태(shape) 텐서 생성
- **torch.tensor(자료구조 \[, dtype\])**
    - 지정한 dtype(Data type)에 맞는 Tensor객체를 생성해서 반환한다.
      
## 특정 타입의 Tensor를 직접 생성
- torch.tensor()로 생성하면서 dtype을 지정하면 아래 타입의 Tensor객체가 생성된다.
- 원하는 Type의 Tensor클래스를 이용해 직접 생성해도 된다.
- **torch.FloatTensor(자료구조)**
    - float32 타입 텐서 생성
- **torch.LongTensor(자료구조)** 
    - int64 타입 텐서생성
- 그외
    - BoolTensor(bool), CharTensor(int8), ShortTensor(int16), IntTensor(int32), DoubleTensor(float64)
    
## tensor 상태 조회
- **tensor.shape, tensor.size(\[축번호\])**
    -  tensor의 shape조회
- **tensor.dtype, tensor.type()**
    - tensor 원소들의 데이터타입 조회
    - dtype은 **data type**을 type()은 tensor **객체의 클래스 타입**을 반환한다.
- **tensor.ndim, tensor.dim()**  : tensor 차원
- **tensor.numel()**: 전체 원소 개수



In [1]:
import torch

In [5]:
torch.float16, torch.float32, torch.float64
torch.int8, torch.int16, torch.int32, torch.int64

(torch.int8, torch.int16, torch.int32, torch.int64)

In [14]:
a = torch.tensor([[1,2],[3,4]], dtype=torch.float32)
print("shape:", a.shape, a.size())
print("0축 크기:", a.shape[0], a.size(0))
# print("축별 크기:", a.shape[0], a.size(0))
print("type:", a.type(), a.dtype)
print('차원크기:', a.dim(), a.ndim)
print('원소개수:', a.numel())
print("device:", a.device)  # tensor를 다루는 processor(메모리위치) - cpu, cuda(gpu)

shape: torch.Size([2, 2]) torch.Size([2, 2])
0축 크기: 2 2
type: torch.FloatTensor torch.float32
차원크기: 2 2
원소개수: 4
device: cpu


In [17]:
aa = torch.tensor(range(10))
aa.dtype
aa.type()

'torch.LongTensor'

In [18]:
#Float, Double(32, 64bit 실수)/Int, Long(32, 64 bit 정수) type Tensor
b = torch.FloatTensor([1,3,7])  #float32
print(b.dtype)
c = torch.IntTensor([10,20,30]) # int64
print(c.dtype)
d = torch.DoubleTensor([1, 2, 3])
print(d.dtype)
e = torch.LongTensor([10, 20, 30, 40])
print(e.dtype)

torch.float32
torch.int32
torch.float64
torch.int64


## 특정(동일한) 값으로 구성된 Tensor 생성
- **torch.zeros(\*size), zeros_like(텐서)**: 0으로 구성된 tensor 생성
- **torch.ones(\*size), ones_like(텐서)**: 1로 구성된 tensor생성
- **torch.full(\*size, fill_value), full_like(텐서, fill_value)**: 지정한 값으로 구성된 tensor생성
    

In [21]:
torch.zeros(3,2,3)
torch.ones(2,3)
torch.full((3,2), fill_value=100)


tensor([[100, 100],
        [100, 100],
        [100, 100]])

In [26]:
a = torch.tensor([[1, 2],[3, 4]]) # 2 x 2
print(a.shape)
b = torch.zeros_like(a)  # a와 같은 shape으로 생성.
b = torch.ones_like(a)
b = torch.full_like(a, 20)
b.shape
# b

torch.Size([2, 2])


tensor([[20, 20],
        [20, 20]])

## 동일한 간격으로 떨어진 값들로 구성된 배열생성
- **torch.arange(start=0, end, step=1)** 
- **torch.linspace(start, end, steps,)** : steps - 원소개수

In [29]:
torch.arange(10)  # end. 0 ~ 10 1씩 증가
torch.arange(0, 1, 0.1) # 0 ~ 1, 0.1 
torch.arange(10, 1, -1) # 10 ~ 1, -1 

tensor([10,  9,  8,  7,  6,  5,  4,  3,  2])

In [31]:
torch.linspace(0, 10, 5)
torch.linspace(0, 1, 11)


tensor([0.0000, 0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000,
        0.9000, 1.0000])

## 빈 tensor 생성
- **torch.empty(\*size)**

In [33]:
torch.empty(3,2,7)

tensor([[[3.1711e-05, 8.1836e-43, 0.0000e+00, 0.0000e+00, 0.0000e+00,
          0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
          0.0000e+00, 0.0000e+00]],

        [[0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
          0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
          0.0000e+00, 0.0000e+00]],

        [[0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
          0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
          0.0000e+00, 0.0000e+00]]])

## 난수를 이용한 생성

- **torch.rand(\*size)**: 0 ~ 1사이 실수로 구성된 배열을 생성. 각 값은 균등분포를 따른다.
- **torch.randn(\*size)**: 표준정규분포(평균:0, 표준편차:1)를 따르는 실수로 구성된 배열 생성
- **torch.randint(low=0, high, size)**: 지정한 범위의 정수로 구성된 배열 생성
- **torch.randperm(n)**: 0 ~ n-1 사이의 정수를 랜덤하게 섞은 값을 원소로 가지는 배열 생성

In [55]:
# torch.manual_seed(0)  # seed 설정
torch.rand(100, 3, 5) #.shape
torch.randn(30,3)
torch.randint(1, 100, (3,3))  
torch.randperm(5) # 0 ~ 4 를 섞어서 구성

tensor([3, 1, 0, 4, 2])

In [58]:
a = torch.arange(100)
# a 섞기
idx = torch.randperm(100) # 0 ~ 99 섞어서 반환. -> index
a[idx]

tensor([ 3, 17, 98, 35, 81, 95,  7, 93, 27, 67, 77, 78, 24, 43, 18, 45,  1, 59,
        26, 61, 22, 10,  8, 74, 62,  4,  0, 60, 89, 90, 92, 38, 73, 41, 99, 37,
        20, 68, 29, 83, 53, 85, 14,  2, 55, 80, 70, 52, 16, 76, 11, 49, 12, 94,
         5, 58, 86,  6, 25, 28, 33, 48, 50, 19, 97, 82, 72, 47, 96, 23, 75, 57,
        39, 30, 87, 31, 71, 44, 40, 88, 34, 15, 63, 46, 65, 64, 21, 13, 56, 91,
        84, 54, 66, 42,  9, 36, 69, 51, 79, 32])

## Tensor gpu/cpu 메모리로 옮기기

- pytorch는 데이터셋인 tensor를 cpu메모리와 gpu 메모리로 서로 옮길 수 있다.
    - 데이터에 대한 연산처리를 어디서 하느냐에 따라 메모리를 선택한다.
    - 장치는 문자열로 설정한다.
        - CPU 사용: "cpu"
        - nvida GPU: "cuda"
        - Apple m1: "mps"
            - pytorch 1.12 부터 지원
- 옮기기
    - tensor 생성시 `device` 파라미터를 이용해 설정
    - `tensor.to(device)`를 이용해 설정
- 현재 실행환경에서 어떤 장비를 사용할 수 있는지 확인
    - nvidia gpu 사용가능확인
        - `torch.cuda.is_available()` - nvida gpu 사용가능 여부
        - `torch.backends.mps.is_available()` - M1 사용가능 여부

In [61]:
# device = 'cuda' if torch.cuda.is_available() else 'mps' if torch.backends.mps.is_available() else 'cpu'
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cpu'

In [67]:
t = torch.tensor([1, 2, 3], dtype=torch.float32, device=device)
t, t.device

t2 = t.to("cpu")
t2, t2.device

(tensor([1., 2., 3.]), device(type='cpu'))

## tensor를 상수로 변환
- torch.Tensor객체를 파이썬 상수로 변환.
- tensor객체.item()
    - Scalar(상수) 또는 원소가 하나인 tensor를 python 상수로 변환

In [71]:
a = torch.tensor(10)  # 상수(scalar) => 0차원
print(a, a.ndim)
print(a.item())
print(type(a), type(a.item()))

tensor(10) 0
10
<class 'torch.Tensor'> <class 'int'>


In [72]:
b = torch.tensor([20])
print(b, b.dim())
print(b.item()) #원소가 하나인 배열(텐서) 변환 가능

tensor([20]) 1
20


In [75]:
c = torch.tensor([1, 10, 100])
print(c)
# print(c.item()) #원소가 여러개일 경우 Exception발생

tensor([  1,  10, 100])


In [ ]:
d = torch.tensor([10], device='cuda')
print(d)
print(d.item())

## ndarray 호환

- ndarray를 tensor로 생성
    - **torch.tensor(ndarray)**
    - **torch.from_numpy(ndarray)**
- tensor를 ndarray로 변환
    - **tensor.numpy()**
    - tensor가 gpu에 있을 경우 cpu로 옮긴 뒤 변환해야 한다.

In [76]:
import numpy as np
import torch

In [79]:
# ndarray -> tensor
arr = np.arange(1,10)

torch.tensor(arr, dtype=torch.float32)
torch.from_numpy(arr)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int32)

In [82]:
# tensor -> ndarray
t = torch.randn(3,3)
print(t)
t.to("cpu").numpy()

tensor([[-1.5411,  0.1133,  1.6016],
        [ 0.6204,  2.0511, -1.8117],
        [-1.3936,  0.5347, -0.9597]])


array([[-1.5410856 ,  0.11329807,  1.601588  ],
       [ 0.6203657 ,  2.0511074 , -1.8116586 ],
       [-1.3936139 ,  0.53468597, -0.95966667]], dtype=float32)

In [ ]:
t2 = torch.randn(2,2, device="cuda")
t2

In [ ]:
t2.numpy() 
# t2.to("cpu").numpy()

# 원소 조회및 변경 - indexing/slicing

- 대부분 Numpy 와 동일
    - **slicing에서 step을 <u>음수로 지정할 수 없다.</u>**


In [83]:
t = torch.randint(-10, 10, (100, ))
t

tensor([  8,  -5,  -2,  -4,  -3,   9,  -5,  -7,   8,  -9,  -9,   9,   9,   7,
         -3,  -9,   1,  -6,   0,  -2,   4,  -8,   3,  -1,   5,  -7,   9,   5,
         -2,   9,  -4,  -5,   3,   4,  -1,   2,   2,  -9,  -4,  -1,   5,  -9,
         -1,   2,   8,  -8,   1,  -2,  -9,   2,   4,   7,   4,  -9,   1,   3,
          0,  -3, -10,   3,   4,   6,   6,  -2,  -2,   6,   0,   9,   1,   1,
         -8,   5,   9,   8,   5,  -9,  -5,  -3,   7,  -1,  -6,  -4,  -6, -10,
          2,   2,  -2, -10,   7,   2, -10,   4,  -4,   7, -10,  -4,   0,  -8,
         -3, -10])

In [85]:
t[0]
t[[1, 5, -1]] # 여러개 조회-> fancy indexing

tensor([ -5,   9, -10])

In [92]:
t[:5]
t[10:15]
t[90:]
t[3:30:3]
# t[10:1:-2]  #에러
t[1:10:2].flip(dims=(0,)) #reverse

tensor([-9, -7,  9, -4, -5])

In [94]:
# boolean index
t[t > 0]

tensor([8, 9, 8, 9, 9, 7, 1, 4, 3, 5, 9, 5, 9, 3, 4, 2, 2, 5, 2, 8, 1, 2, 4, 7,
        4, 1, 3, 3, 4, 6, 6, 6, 9, 1, 1, 5, 9, 8, 5, 7, 2, 2, 7, 2, 4, 7])

In [95]:
t

tensor([  8,  -5,  -2,  -4,  -3,   9,  -5,  -7,   8,  -9,  -9,   9,   9,   7,
         -3,  -9,   1,  -6,   0,  -2,   4,  -8,   3,  -1,   5,  -7,   9,   5,
         -2,   9,  -4,  -5,   3,   4,  -1,   2,   2,  -9,  -4,  -1,   5,  -9,
         -1,   2,   8,  -8,   1,  -2,  -9,   2,   4,   7,   4,  -9,   1,   3,
          0,  -3, -10,   3,   4,   6,   6,  -2,  -2,   6,   0,   9,   1,   1,
         -8,   5,   9,   8,   5,  -9,  -5,  -3,   7,  -1,  -6,  -4,  -6, -10,
          2,   2,  -2, -10,   7,   2, -10,   4,  -4,   7, -10,  -4,   0,  -8,
         -3, -10])

In [96]:
# 변경
t[0] = 100
t

tensor([100,  -5,  -2,  -4,  -3,   9,  -5,  -7,   8,  -9,  -9,   9,   9,   7,
         -3,  -9,   1,  -6,   0,  -2,   4,  -8,   3,  -1,   5,  -7,   9,   5,
         -2,   9,  -4,  -5,   3,   4,  -1,   2,   2,  -9,  -4,  -1,   5,  -9,
         -1,   2,   8,  -8,   1,  -2,  -9,   2,   4,   7,   4,  -9,   1,   3,
          0,  -3, -10,   3,   4,   6,   6,  -2,  -2,   6,   0,   9,   1,   1,
         -8,   5,   9,   8,   5,  -9,  -5,  -3,   7,  -1,  -6,  -4,  -6, -10,
          2,   2,  -2, -10,   7,   2, -10,   4,  -4,   7, -10,  -4,   0,  -8,
         -3, -10])

In [97]:
t = torch.arange(1, 10).reshape(3,3)
t

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [102]:
# t[ 0축, 1축 ]
t[1, 2].item()
t[0, 2].item()

3

In [103]:
t[[1,0], [2,2]]  #(1,2), (0,2)
# t[[첫번째값, 두번째값]-0축, [첫번째값, 두번째값]-1축]

tensor([6, 3])

# Reshape

## shape 변경
- tensor객체.reshape(\*shape) / view(\*shape) 이용
    - 변환 후 값을 변경하면 원본 배열의 값도 같이 바뀐다.
 > tensor.clone(): tensor를 복제한다.

In [104]:
a=torch.rand(12)
a2 = a.reshape(3,4)
a3 = a.reshape((3,2,2))
a4 = a.reshape((3,2,-1))  #한 개 axis는 -1로 설정가능하고 그럼 계산해서 알아서 설정해 준다.
print(a.shape, a2.size(), a3.shape, a4.shape)
               

torch.Size([12]) torch.Size([3, 4]) torch.Size([3, 2, 2]) torch.Size([3, 2, 2])


In [105]:
a

tensor([0.9282, 0.5047, 0.9981, 0.7799, 0.4581, 0.8077, 0.8010, 0.4165, 0.2189,
        0.2476, 0.9483, 0.9787])

In [106]:
a2

tensor([[0.9282, 0.5047, 0.9981, 0.7799],
        [0.4581, 0.8077, 0.8010, 0.4165],
        [0.2189, 0.2476, 0.9483, 0.9787]])

In [107]:
a5 = a.view(3,4)
a6 = a.view((3,2,2))
a7 = a.view((3,2,-1))  #한개 axis는 -1로 설정가능
print(a.shape, a5.size(), a6.shape, a7.shape)

torch.Size([12]) torch.Size([3, 4]) torch.Size([3, 2, 2]) torch.Size([3, 2, 2])


In [108]:
a

tensor([0.9282, 0.5047, 0.9981, 0.7799, 0.4581, 0.8077, 0.8010, 0.4165, 0.2189,
        0.2476, 0.9483, 0.9787])

In [109]:
a5  # a.view(3, 4)

tensor([[0.9282, 0.5047, 0.9981, 0.7799],
        [0.4581, 0.8077, 0.8010, 0.4165],
        [0.2189, 0.2476, 0.9483, 0.9787]])

In [111]:
a2  # a.reshape(3,4)

tensor([[12.1000,  0.5047,  0.9981,  0.7799],
        [ 0.4581,  0.8077,  0.8010,  0.4165],
        [ 0.2189,  0.2476,  0.9483,  0.9787]])

In [112]:
# a5[0, 0] = 12.1
a2[0, 1] = 15.1

print(a)

tensor([12.1000, 15.1000,  0.9981,  0.7799,  0.4581,  0.8077,  0.8010,  0.4165,
         0.2189,  0.2476,  0.9483,  0.9787])


In [114]:
a4

tensor([[[12.1000, 15.1000],
         [ 0.9981,  0.7799]],

        [[ 0.4581,  0.8077],
         [ 0.8010,  0.4165]],

        [[ 0.2189,  0.2476],
         [ 0.9483,  0.9787]]])

In [115]:
# tensor복사: clone() 메소드
r = a.clone().reshape(3,4)
r[0,0] = 100.1
print(a)

tensor([12.1000, 15.1000,  0.9981,  0.7799,  0.4581,  0.8077,  0.8010,  0.4165,
         0.2189,  0.2476,  0.9483,  0.9787])


## dummy 축 늘리기

- None을 이용 (numpy의 newaxis 대신 None을 사용한다.)
- unsqueeze(dim=축번호)

In [119]:
import torch
a = torch.tensor([[10,20],[10,20]])
print(a.shape)

a1, a2 = a[None, :], a.unsqueeze(dim=0)
print(a1.shape, a2.shape)

a3, a4 = a[:, :, None], a.unsqueeze(dim=-1) 
print(a3.shape, a4.shape)

a5, a6 = a3[:,None,:,:], a3.unsqueeze(dim=1)
print(a5.shape, a6.shape)

torch.Size([2, 2])
torch.Size([1, 2, 2]) torch.Size([1, 2, 2])
torch.Size([2, 2, 1]) torch.Size([2, 2, 1])
torch.Size([2, 1, 2, 1]) torch.Size([2, 1, 2, 1])


## dummy 축 제거
- squeeze(\[dim=축번호\]) 이용

In [125]:
t = torch.rand(3, 1, 4, 1, 5, 1)
print(t.shape)

r1 = t.squeeze()  #축을 명시 하지 않으면 모두 제거
print(r1.shape)

r2 = t.squeeze(dim=1) # 특정 axis 제거
print(r2.shape)

r3 = t.squeeze(dim=[1,3]) # 여러 axis의 dummy 축 제거
print(r3.shape)

torch.Size([3, 1, 4, 1, 5, 1])
torch.Size([3, 4, 5])
torch.Size([3, 4, 1, 5, 1])
torch.Size([3, 4, 5, 1])


## tensor 합치기
torch.cat([tensorA, tensorB, ...], dim=0) : 기준축 default 는 0

In [126]:
a = torch.arange(10).reshape(2,5)
b = torch.arange(10,20).reshape(2,5)
c = torch.arange(20,30).reshape(2,5)
d = torch.arange(10,19).reshape(3,3)
print(a)
print(b)
print(c)
print(d)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])
tensor([[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])
tensor([[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]])
tensor([[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]])


In [128]:
torch.cat([a, b], dim=0)

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])

In [129]:
torch.cat([a, b, c], dim=0)

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]])

In [130]:
torch.cat([a, b], axis=1) # dim 대신 axis사용가능

tensor([[ 0,  1,  2,  3,  4, 10, 11, 12, 13, 14],
        [ 5,  6,  7,  8,  9, 15, 16, 17, 18, 19]])

In [131]:
torch.cat([a, b, c], axis=1)

tensor([[ 0,  1,  2,  3,  4, 10, 11, 12, 13, 14, 20, 21, 22, 23, 24],
        [ 5,  6,  7,  8,  9, 15, 16, 17, 18, 19, 25, 26, 27, 28, 29]])

In [133]:
torch.cat([a, b], axis=-1)  # -1: 마지막 axis

tensor([[ 0,  1,  2,  3,  4, 10, 11, 12, 13, 14],
        [ 5,  6,  7,  8,  9, 15, 16, 17, 18, 19]])

In [136]:
a.shape, d.shape
# 합치는 기준축 이외의 축 size는 같아야 한다.
# torch.cat([a, d])  #dim=0, Error  1축 size가 달라서 Error

(torch.Size([2, 5]), torch.Size([3, 3]))

## 값의 위치(index) 변경
- tensor 원소의 축별 index의 위치를 바꾼다.
- `tensor.transpose(axis1, axis2)` 
    - 두 축의 자리만 변경 할 수 있다.
- `tensor.permute(axis1, axis2, axis3, ..)`
    - 두 개 이상의 축 자리를 변경한다.

In [142]:
X = torch.arange(24).reshape(2, 3, 4)
print(X.shape)
# X
y = X.transpose(1, 2)
print(y.shape)

z = X.permute(2, 0, 1)
print(z.shape)

torch.Size([2, 3, 4])
torch.Size([2, 4, 3])
torch.Size([4, 2, 3])


# tensor 연산 및 주요 함수

## element-wise 연산
- tensor와 상수 연산시, tensor와 tensor간 연산시 원소별로 처리한다.
- 행렬곱 연산을 제외하고 tensor간 연산시 피연산지 tensor간에 shape이 같아야 한다.
    - shape이 다를 경우 조건이 맞으면 broadcasting을 한 뒤에 연산한다. (size가 다른 축의 경우 한개의 피연산자 size가 1일 경우 복사하여 shape을 맞춘다.)
    

In [143]:
import torch

a = torch.arange(10).reshape(2,5)
b = torch.arange(10,20).reshape(2,5)
c = torch.arange(50, 55)

print(a)
print(b)
print(c)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])
tensor([[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])
tensor([50, 51, 52, 53, 54])


In [146]:
print(a + 100)
print(a - 100)
print(a < 5)

tensor([[100, 101, 102, 103, 104],
        [105, 106, 107, 108, 109]])
tensor([[-100,  -99,  -98,  -97,  -96],
        [ -95,  -94,  -93,  -92,  -91]])
tensor([[ True,  True,  True,  True,  True],
        [False, False, False, False, False]])


In [148]:
print(a + b)
print(a == b)

tensor([[10, 12, 14, 16, 18],
        [20, 22, 24, 26, 28]])
tensor([[False, False, False, False, False],
        [False, False, False, False, False]])


In [149]:
a.size(), c.size()

(torch.Size([2, 5]), torch.Size([5]))

In [150]:
# broadcasting
print(a + c)

tensor([[50, 52, 54, 56, 58],
        [55, 57, 59, 61, 63]])


## 주요 연산함수

In [158]:
torch.e, np.e

(2.718281828459045, 2.718281828459045)

In [162]:
x=torch.arange(-4, 5).reshape(3,3)
print(x)
print(torch.abs(x)) # 절대값 
print(torch.sqrt(torch.abs(x))) #  제곱근
print(torch.exp(x))  # torch.e**x
print(torch.log(torch.abs(x)))
print(torch.log(torch.exp(torch.tensor(1))))  # torch.log() 밑이 e인 로그계산
print(torch.log10(torch.tensor(10)))         # torch.log10() 밑이 10인 로그계산
print(torch.log2(torch.tensor(2)))           # torch.log2() 밑이 2인 로그계산
# print("=====================")

tensor([[-4, -3, -2],
        [-1,  0,  1],
        [ 2,  3,  4]])
tensor([[4, 3, 2],
        [1, 0, 1],
        [2, 3, 4]])
tensor([[2.0000, 1.7321, 1.4142],
        [1.0000, 0.0000, 1.0000],
        [1.4142, 1.7321, 2.0000]])
tensor([[1.8316e-02, 4.9787e-02, 1.3534e-01],
        [3.6788e-01, 1.0000e+00, 2.7183e+00],
        [7.3891e+00, 2.0086e+01, 5.4598e+01]])
tensor([[1.3863, 1.0986, 0.6931],
        [0.0000,   -inf, 0.0000],
        [0.6931, 1.0986, 1.3863]])
tensor(1.)
tensor(1.)
tensor(1.)


In [166]:
y = x + torch.randn((3,3))
print(y)
print(torch.round(y)) # 반올림
print(torch.round(y, decimals=2)) # 소수점 둘째자리 이하에서 반올림
print(torch.floor(y)) # 내림
print(torch.ceil(y)) # 올림

tensor([[-2.9531, -3.1256, -2.4183],
        [-2.1837,  1.5501,  0.1452],
        [ 1.9784,  2.5237,  4.6883]])
tensor([[-3., -3., -2.],
        [-2.,  2.,  0.],
        [ 2.,  3.,  5.]])
tensor([[-2.9500, -3.1300, -2.4200],
        [-2.1800,  1.5500,  0.1500],
        [ 1.9800,  2.5200,  4.6900]])
tensor([[-3., -4., -3.],
        [-3.,  1.,  0.],
        [ 1.,  2.,  4.]])
tensor([[-2., -3., -2.],
        [-2.,  2.,  1.],
        [ 2.,  3.,  5.]])


### 행렬곱
- `@` 연산자 또는 `torch.matmul(tensor1, tensor2)` 함수 이용

In [ ]:
import torch

In [167]:
x = torch.FloatTensor([[1, 2],[3, 4],[5, 6]])

y = torch.FloatTensor([[1, 2],[1, 2],])
x.size(), y.shape

(torch.Size([3, 2]), torch.Size([2, 2]))

In [168]:
z1 = x @ y
z2 = torch.matmul(x, y)
print(z1.shape, z2.shape)
print(z1)
print(z2)

torch.Size([3, 2]) torch.Size([3, 2])
tensor([[ 3.,  6.],
        [ 7., 14.],
        [11., 22.]])
tensor([[ 3.,  6.],
        [ 7., 14.],
        [11., 22.]])


In [169]:
# Batch 행렬곱(Batch matrix muliplication) - bmm()
# x, y가 가지는 3개의 2차원 배열 간에 행렬곱을 처리한다.
import torch
x = torch.FloatTensor(3,4,2)
y = torch.FloatTensor(3,2,5)
z = torch.bmm(x, y)
z.shape


torch.Size([3, 4, 5])

## torch.nan, torch.inf
- nan: Not a Number, 주로 결측치를 표현한다.
- inf: infinit 무한. 
    - torch.inf: 양의 무한
    - -torch.inf: 음의 무한
- torch.isnan(tensor)
    - 원소별 결측치 확인
- torch.isinf(tensor)    
    - 원소별 inf 확인

In [174]:
print(torch.inf > 100000000, torch.inf < 10)
print(-torch.inf < 10, -torch.inf > 10)

True False
True False


In [177]:
print(torch.log(torch.tensor(-1))) # nan (계산결과가 없으므로-없는값-nan 반환)
print(torch.isnan(torch.tensor([1,2,torch.nan,3,4])))  # nan 여부 확인
print(torch.isinf(torch.tensor([1,2,3,4,torch.inf])))  # inf 여부 확인

tensor(nan)
tensor([False, False,  True, False, False])
tensor([False, False, False, False,  True])


## 기술통계함수

In [178]:
X=torch.randn(3,4)
print(X)

tensor([[ 0.1696,  0.6549,  0.3477,  0.1323],
        [ 0.0721, -0.8358, -0.9632,  0.2658],
        [-0.1939,  1.0105,  0.8049,  0.7527]])


In [181]:
print(torch.sum(X))  # default: 전체기준으로 계산. dim=None
print(torch.sum(X, dim=1)) #dim/axis 지정: 지정한 axis의 index가 다른 값끼리 계산.
print(torch.sum(X, dim=1, keepdims=True))

tensor(2.2173)
tensor([ 1.3044, -1.4613,  2.3742])
tensor([[ 1.3044],
        [-1.4613],
        [ 2.3742]])


In [187]:
print(torch.mean(X))
print(torch.mean(X, dim=1))
print(torch.mean(X, dim=1, keepdims=True))

tensor(0.1848)
tensor([ 0.3261, -0.3653,  0.5935])
tensor([[ 0.3261],
        [-0.3653],
        [ 0.5935]])


In [190]:
print(torch.std(X)) # standard deviation 표준 편차
print(torch.var(X)) # variance
print(torch.var(X, dim=0))

tensor(0.6151)
tensor(0.3783)
tensor([0.0354, 0.9596, 0.8423, 0.1067])


In [191]:
# tensor.메소드() 
print(X.sum(dim=1, keepdims=True))
print(X.mean(dim=1, keepdims=True))
print(X.std())

tensor([[ 1.3044],
        [-1.4613],
        [ 2.3742]])
tensor([[ 0.3261],
        [-0.3653],
        [ 0.5935]])
tensor(0.6151)


In [193]:
X

tensor([[ 0.1696,  0.6549,  0.3477,  0.1323],
        [ 0.0721, -0.8358, -0.9632,  0.2658],
        [-0.1939,  1.0105,  0.8049,  0.7527]])

In [199]:
# print(torch.max(X))
# print(torch.max(X, dim=0))  # return_types.max 타입객체로 반환. max값과 max값의 index를 묶어서 반환
# print(torch.max(X, dim=1))
# print(torch.max(X, dim=1).values, torch.max(X, dim=1).indices, sep=" || ")
# print(torch.max(X, dim=0, keepdims=True))  #keepdims=True : 차원(rank)를 유지
print(torch.max(X, dim=1, keepdims=True))

torch.return_types.max(
values=tensor([[0.6549],
        [0.2658],
        [1.0105]]),
indices=tensor([[1],
        [3],
        [1]]))


In [205]:
# print(torch.min(X))
# print(torch.min(X, dim=0))
# print(torch.min(X, dim=1))

# print(torch.argmax(X))
print(torch.argmax(X, dim=0)) # 각 열에서 가장 큰 애가 존재하는 인덱스
# print(torch.argmax(X, dim=1)) # 각 행에서 가장 큰 애가 존재하는 인덱스

tensor([0, 2, 2, 2])


In [208]:
a = torch.max(X, dim=0)
print(a.values)
print(a.indices)

tensor([0.1696, 1.0105, 0.8049, 0.7527])
tensor([0, 2, 2, 2])


In [209]:
torch.argmin(X, dim=0)

tensor([2, 1, 1, 0])

# autograd(자동미분)
- 자동 미분을 이용해 gradient(미분계수)를 계산하는 pytorch system.
- 딥러닝 모델에서 weight와 bias tensor들(Parameter)은 backpropagation(역전파)를 이용해 gradient를 구해서 loss가 줄어드는 방향으로 update를 하게된다.
- pytorch는 이런 미분 수행을 자동으로 처리해 준다.
    - gradient(기울기)를 구한다는 것은 미분을 한다는 것을 말한다.
- tensor가 미분 가능하려면(gradient 계산 대상 변수) `requires_grad=True` 로 설정되 있어야 한다. (default: False)
    

In [1]:
import torch

In [2]:
# requires_grad 속성은 생성시 지정, 생성후 지정(변경)할 수있다.
x = torch.tensor([1.0], requires_grad=True)  # gradient구할 대상.(딥러닝모델-파라미터들)

# x.requires_grad = True
print(x.requires_grad)
print(x.grad)   # tensor.grad: 계산된 gradient를 저장하는 속성.
# print(x.data)   # tensor.data: Tensor의 배열(값들)을 저장하는 속성.

True
None


In [3]:
y = x**2
print("결과:", y, y.data)
# y는 requires_grad=True인 값을 이용해 연산한 함수. -> grad_fn 속성: 함수 y의 도함수
print(y.grad_fn)

결과: tensor([1.], grad_fn=<PowBackward0>) tensor([1.])


In [35]:
# x의 gradient를 계산. grad_fn은 y에 있다. 
y.backward()   # gradient 계산하고 그 결과를  x(requires_grad=True)의 grad 속성에  저장
# dy/dx

In [36]:
x.grad

tensor([2.])

In [47]:
##### vector(여러개값들)에 대한 미분.
x = torch.tensor([1.0, 2.0, 3.0], requires_grad=True)
y = torch.sum(x**2)    # [1.0**2 + 2.0**2 + 3.0**2]
y

tensor(14., grad_fn=<SumBackward0>)

In [48]:
x**2

tensor([1., 4., 9.], grad_fn=<PowBackward0>)

In [44]:
y.backward()

In [45]:
x.grad

tensor([2., 4., 6.])

In [57]:
#### 합성 함수 미분.   f(g(x))   
###### 함수에 미분가능한 변수가 여러개 일 경우 편미분 -> 각각 따로 gradient를 계산.
a = torch.tensor([1.], requires_grad=True)
b = torch.tensor([2.], requires_grad=True)
y = a**2
z = y * b   # (a**2) * b
print(y.item(), z.item())
print(y.grad_fn)
print(z.grad_fn)

1.0 2.0


In [58]:
y.requires_grad

True

In [53]:
z.backward()

In [56]:
print("변수 b의 grad값:", b.grad)  # dz / db
print("변수 a의 grad값:", a.grad)  # dz / da

변수 b의 grad값: tensor([1.])
변수 a의 grad값: tensor([4.])


## torch.no_grad() 
- no_grad() 구문에서 연산을 할 경우 requires_grad=True로 설정되었다 하더라도 gradient를 update하지 않는다.
- 딥러닝 모델 학습이 끝나고 평가할 때는 gradient를 계산할 필요가 없기 때문에 no_grad 구문을 사용한다.


In [83]:
x = torch.tensor(1.0, requires_grad=True)
print(x.requires_grad)

y = x ** 2  # y.grad_fn : 도함수
print(y, y.requires_grad)
print(x.grad)
y.backward()
print(x.grad)

True
tensor(1., grad_fn=<PowBackward0>) True
None
tensor(2.)


In [5]:
# with문 안에서 requires_grad=True인 변수를 이용해 연산하더라도 
#                                                                         gradient는 구하지 안는다.
print(x.requires_grad)
y2 = x ** 2
print(y2.grad_fn)
with torch.no_grad():  ### 모델 평가/검증/추론 코드.
    y2 = x ** 2  # x: requires_grad=True -> gradient를 계산 안할 것.-> y2.grad_fn 생성안한다.

print(x.requires_grad)
print(y2.requires_grad)
print(y2.grad_fn)
# y2.backward()    

True
True
False
None


## gradient 값 초기화

In [80]:
x = torch.tensor(1.0, requires_grad=True)
y = x ** 2    # grad_fn: 2 * X
y.backward()
print("x의 gradient값: ", x.grad)

x의 gradient값:  tensor(2.)


In [ ]:
### 변수 x를 이용해서 새로운 계산.

In [81]:
# requires_grad=True인 변수로 새로운 연산을 할 경우 grad값을 초기화.( None)
### 초기화 하지 않으면 gradient값이 계속 더해진다.
x.grad = None  # 초기화
print(x.data)
z = x ** 3   # grad_fn: 3 * X**2
z.backward()
print("z에대한 x의 gradient값:", x.grad)

tensor(1.)
z에대한 x의 gradient값: tensor(3.)


In [82]:
x.grad = None
print(x.data)
r = x ** 2  # grad_fn: 2 * x
r.backward()
print("r에대한 x의 gradient값:", x.grad) 

tensor(1.)
r에대한 x의 gradient값: tensor(2.)
